# Generated by Django 3.2 on 2021-05-03 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210430_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
