# Generated by Django 3.2 on 2021-04-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='packages_size',
            field=models.IntegerField(default=0),
        ),
    ]
