# Generated by Django 3.2 on 2021-04-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_packages_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='packages_size',
        ),
    ]
